// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SymulatroLinii.Model;

namespace SymulatroLinii.Migrations
{
    [DbContext(typeof(DbSerwerSQLite.DbSerwerContext))]
    partial class DbSerwerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("SymulatroLinii.Model.DbSerwerSQLite+DbSerwer", b =>
                {
                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Haslo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.HasKey("Nazwa");

                    b.ToTable("DbSerwers");
                });
#pragma warning restore 612, 618
        }
    }
}
